# Generated by Django 6.0.5 on 2026-05-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at'], 'verbose_name': 'Bài viết', 'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Chủ đề', 'verbose_name_plural': 'Chủ đề'},
        ),
    ]
