# Generated by Django 6.0.5 on 2026-05-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_options_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(blank=True, choices=[('thac_mac', 'Thắc mắc'), ('thao_luan', 'Thảo luận'), ('danh_gia', 'Đánh giá'), ('chia_se', 'Chia sẻ'), ('huong_dan', 'Hướng dẫn')], max_length=20, null=True, verbose_name='Tag'),
        ),
    ]
